if ($ENV{SOC} MATCHES j721e)
    set (BUILD_CPU      yes)
    set (MPU_CPU        a72)
    set (BUILD_MCU      yes)
    set (BUILD_C7X      yes)
    set (BUILD_C6X      yes)
elseif ($ENV{SOC} MATCHES j721s2)
    set (BUILD_CPU      yes)
    set (MPU_CPU        a72)
    set (BUILD_MCU      yes)
    set (BUILD_C7X      yes)
    set (BUILD_C6X      no )
elseif ($ENV{SOC} MATCHES j784s4)
    set (BUILD_CPU      yes)
    set (MPU_CPU        a72)
    set (BUILD_MCU      yes)
    set (BUILD_C7X      yes)
    set (BUILD_C6X      no )
elseif ($ENV{SOC} MATCHES am62a)
    set (BUILD_CPU      yes)
    set (MPU_CPU        a53)
    set (BUILD_MCU      yes)
    set (BUILD_C7X      yes)
    set (BUILD_C6X      no )
else()
endif()