if (NOT DEFINED ENV{CORE})
    message(WARNING "Core not defined.")
endif()

if (NOT DEFINED ENV{TISDK_PATH})
    message(WARNING "Toolchain path not defined.")
endif()

if ("$ENV{CORE}" STREQUAL "a72" OR "$ENV{CORE}" STREQUAL "a53")
    set(CMAKE_SYSTEM_NAME       Linux)
    set(CMAKE_SYSTEM_PROCESSOR  aarch64)
    set(CROSS_COMPILER_PATH     $ENV{TISDK_PATH}/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu)
    set(CROSS_COMPILER_PREFIX   aarch64-none-linux-gnu-)
    set(TOOLCHAIN_PREFIX        ${CROSS_COMPILER_PATH}/bin/${CROSS_COMPILER_PREFIX})
    set(CMAKE_C_COMPILER        ${TOOLCHAIN_PREFIX}gcc)
    set(CMAKE_CXX_COMPILER      ${TOOLCHAIN_PREFIX}g++)
else()
    message(WARNING "CROSS_COMPILER_PATH not defined, Using default TOOLCHAIN")
endif()

if (DEFINED ENV{SOC_TARGET_FS})
    set(CMAKE_SYSROOT           $ENV{SOC_TARGET_FS})
else()
    message(WARNING "TARGET_FS not defined, Using /")
endif()
